# The Battle of the Neighborhoods - Week 1

## Introduction &  Analysis of this Project :

I have lived in Seoul, Toronto, LA and currently living in Austin.
Since I have lived in so many different cities, pleople often ask me which city is best for the living ?
Good question, which I am trying to answer it but it may not simple.. 

### Comparions between Cities(Los Angeles,Austin,Toronto,Seoul)

These are all good size cities and depending on the neighbourhood, it could quite different ..
So, I will focus on neighbours where I have lived
Los Angenes - San Pedro
Austin - Avery Ranch area North of city
Toronto - Scarbourgh
Seoul - Gangnam  , Yes, I am from Gangnam !! -- Rerember ? - Gangname Style ? - Lol
I will compare with data from foursqure and comparing attractive venues and other possible factors provided by foursquare.

### Which City is best for living - possible factors I can think of:

- Population
- Demographics
- Shopping Centers
- Restaurants with differt nationalities - Korean/Japanese,Italian,Indian,Chineses,American...
- Parks & Recreations - Soccer field,tennis courts ..
- Traffic 
- Polution/Air quality
- Professional sports teams(NFL,NBA,MLS,MLB...)
- Crime rates/squre Km
- Average temperature for whole year
- Average life expectacy.

Unfortunately, I don't expect to get all these possible factors from Foursquare.. -- may need to premium or more website needed -- will skip those :)
Also, we can prioritize these factors with givine the different weigh 
- Example
- Parks & Recreations - 3 points
- Traffic  - 2 points
- Average life expectacy - 1 points

### Different Viewpoints and missing Informations:

In general, everyone has differnt point of view about living.
Some people , like me , playing soccer and watching soccer is my favorite hobby and lifestyle while others have different priorities in their life
So, this original question - which City/neighbour is best for living  could became very objective , meaning different for different for individuals.

In a short words, It is completely up the personal. Meaning not exactly be the location or neighbourhood.

### Final Outcome : Generalizations and Clustering

At the end, it could possbily be category/clustering for differnt people as groups like
Young people tend to like living in a big city like LA,Seoul and Toronto, while older people like to live in small city like Austin
Also from different priorities could effect for individuals or group of people

Anyways, I will choose my definition of best place to live based on my findings and unknowns.

I think, Scope of this projects is beyond this course  , I am planning to go on after this course .. Very interesting !!

# The Battle of the Neighborhoods - Week 2 - Coding Starts from Here

In [ ]:
import numpy as np # library to handle data in a vectorized manner
import time
import pandas as pd # library for data analsysis
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import json # library to handle JSON files
import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

from geopy.geocoders import Nominatim # convert an address into latitude and longitude values
!conda install -c conda-forge folium=0.5.0 --yes # uncomment this line if you haven't completed the Foursquare API lab
import folium # map rendering library

print('Libraries imported.')

In [92]:
# Shenton Way, District 01, Singapore
address = 'Gangnam, Korea'
geolocator = Nominatim()
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Gangnam are {}, {}.'.format(latitude, longitude))

address2 = 'San Pedro, Los Angeles'
geolocator2 = Nominatim()
location2 = geolocator2.geocode(address2)
latitude2 = location2.latitude
longitude2 = location2.longitude
print('The geograpical coordinate of San Pedro home are {}, {}.'.format(latitude2, longitude2))

address3 = 'Scarborough, Toronto'
geolocator3 = Nominatim()
location3 = geolocator3.geocode(address3)
latitude3 = location3.latitude
longitude3 = location3.longitude
print('The geograpical coordinate of Scarbourgh home are {}, {}.'.format(latitude3, longitude3))

address4 = 'Avery Ranch, Austin'
geolocator4 = Nominatim()
location4 = geolocator4.geocode(address4)
latitude4 = location4.latitude
longitude4 = location4.longitude
print('The geograpical coordinate of Avery Ranch home are {}, {}.'.format(latitude4, longitude4))

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:3: DeprecationWarning: Using Nominatim with the default "geopy/1.18.1" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  app.launch_new_instance()

The geograpical coordinate of Gangnam are 37.4979002, 127.0276077.

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:10: DeprecationWarning: Using Nominatim with the default "geopy/1.18.1" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.

The geograpical coordinate of San Pedro home are 33.7358518, -118.2922934.

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:17: DeprecationWarning: Using Nominatim with the default "geopy/1.18.1" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.

The geograpical coordinate of Scarbourgh home are 43.773077, -79.257774.

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:24: DeprecationWarning: Using Nominatim with the default "geopy/1.18.1" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.

The geograpical coordinate of Avery Ranch home are 30.5105061, -97.7486707.

In [93]:
neighborhood_latitude=37.4979
neighborhood_longitude=127.03

In [94]:
CLIENT_ID = '5U4GIAWTHEMVRX52T3340F5TFAOVVLZJHJI14ZDMLH1GZMFO' # your Foursquare ID
CLIENT_SECRET = 'GFZQCY52JYDZWV4ZMVDXZPM2JVV0XOUX3OTXKYOZCOEY5YC3' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: 5U4GIAWTHEMVRX52T3340F5TFAOVVLZJHJI14ZDMLH1GZMFO
CLIENT_SECRET:GFZQCY52JYDZWV4ZMVDXZPM2JVV0XOUX3OTXKYOZCOEY5YC3

In [107]:
# type your answer here
LIMIT = 100 # limit of number of venues returned by Foursquare API

radius = 500 # define radius
 # create URL
url_gn = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude, 
    neighborhood_longitude, 
    radius, 
    LIMIT)
url_sp = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    latitude2, 
    longitude2, 
    radius, 
    LIMIT)
url_sb = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    latitude3, 
    longitude3, 
    radius, 
    LIMIT)
url_av = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    latitude4, 
    longitude4, 
    radius, 
    LIMIT)
#url_gn # display URL
url_av # display URL

'https://api.foursquare.com/v2/venues/explore?&client_id=5U4GIAWTHEMVRX52T3340F5TFAOVVLZJHJI14ZDMLH1GZMFO&client_secret=GFZQCY52JYDZWV4ZMVDXZPM2JVV0XOUX3OTXKYOZCOEY5YC3&v=20180605&ll=30.5105061,-97.7486707&radius=500&limit=100'

In [108]:
results_gn = requests.get(url_gn).json()
results_sp = requests.get(url_sp).json()
results_sb = requests.get(url_sb).json()
results_av = requests.get(url_av).json()
#results_gn

In [45]:
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

In [109]:
# Nearby Venues for Gangnam
venues_gn = results_gn['response']['groups'][0]['items']
nearby_venues_gn = json_normalize(venues_gn) # flatten JSON
# filter columns
filtered_columns_gn = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues_gn =nearby_venues_gn.loc[:, filtered_columns]
# filter the category for each row
nearby_venues_gn['venue.categories'] = nearby_venues_gn.apply(get_category_type, axis=1)
# clean columns
nearby_venues_gn.columns = [col.split(".")[-1] for col in nearby_venues_gn.columns]

# Nearby Venues for San Pedro
venues_sp = results_sp['response']['groups'][0]['items']
nearby_venues_sp = json_normalize(venues_sp) # flatten JSON
# filter columns
filtered_columns_sp = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues_sp =nearby_venues_sp.loc[:, filtered_columns]
# filter the category for each row
nearby_venues_sp['venue.categories'] = nearby_venues_sp.apply(get_category_type, axis=1)
# clean columns
nearby_venues_sp.columns = [col.split(".")[-1] for col in nearby_venues_sp.columns]

# Nearby Venues for Scarbourgh
venues_sb = results_sb['response']['groups'][0]['items']
nearby_venues_sb = json_normalize(venues_sb) # flatten JSON
# filter columns
filtered_columns_sb = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues_sb =nearby_venues_sb.loc[:, filtered_columns]
# filter the category for each row
nearby_venues_sb['venue.categories'] = nearby_venues_sb.apply(get_category_type, axis=1)
# clean columns
nearby_venues_sb.columns = [col.split(".")[-1] for col in nearby_venues_sb.columns]
#nearby_venues_gn.head(10)

# Nearby Venues for Avery Ranch
venues_av = results_av['response']['groups'][0]['items']
nearby_venues_av = json_normalize(venues_av) # flatten JSON
# filter columns
filtered_columns_av = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues_av =nearby_venues_av.loc[:, filtered_columns]
# filter the category for each row
nearby_venues_av['venue.categories'] = nearby_venues_av.apply(get_category_type, axis=1)
# clean columns
nearby_venues_av.columns = [col.split(".")[-1] for col in nearby_venues_av.columns]
nearby_venues_av.head(10)

                            name categories        lat        lng
0  Waters Edge Pool: Avery Ranch       Pool  30.510328 -97.748672

In [110]:
print('{} venues were returned by Foursquare.'.format(nearby_venues_av.shape[0]))

1 venues were returned by Foursquare.

In [111]:
# create map of Each neighbour latitude and longitude values
map_gangnam = folium.Map(location=[latitude, longitude], zoom_start=20)
map_sanpedro = folium.Map(location=[latitude2, longitude2], zoom_start=20)
map_scarbro = folium.Map(location=[latitude3, longitude3], zoom_start=20)
map_averyran = folium.Map(location=[latitude4, longitude4], zoom_start=20)
map_averyran # view my current Neighbour - Avery Ranch Austin

In [104]:
# View the Resaurants near Gangnam
club_gn=nearby_venues_gn
restaurant_gn=club_gn[club_gn['categories'].str.contains("Restaurant")]
restaurant_gn.head(5)

               name             categories        lat         lng
5             단풍나무집      Korean Restaurant  37.498724  127.029764
6              갓덴스시       Sushi Restaurant  37.498510  127.029238
7     CUCHARA (쿠차라)     Mexican Restaurant  37.497337  127.026569
13       emoi (에머이)  Vietnamese Restaurant  37.496563  127.029471
14  Kiriyama (기리야마)    Japanese Restaurant  37.496997  127.030294

In [123]:
# View the Restaurant near Scarbourgh
club_sb=nearby_venues_sb
g_club_sb=club_sb[club_sb['categories'].str.contains("Rest")]
g_club_sb

                      name           categories        lat        lng
5   Chipotle Mexican Grill   Mexican Restaurant  43.776410 -79.258069
11         Jimmy The Greek     Greek Restaurant  43.775112 -79.257119
16   Moxie's Classic Grill  American Restaurant  43.776219 -79.256820
32            Thai Express           Restaurant  43.776692 -79.259162

In [113]:
# View the Venues near Gangnam
nearby_venues_gn['categories'].value_counts()

Coffee Shop              16
Korean Restaurant        11
BBQ Joint                 7
Japanese Restaurant       5
Sushi Restaurant          5
Chinese Restaurant        4
Seafood Restaurant        3
Vietnamese Restaurant     3
Sandwich Place            3
Smoothie Shop             2
Steakhouse                2
Café                      2
Breakfast Spot            2
Bakery                    2
Noodle House              2
Bar                       1
Rental Service            1
Salad Place               1
Golf Course               1
Beer Garden               1
Bubble Tea Shop           1
Rock Club                 1
Electronics Store         1
Beer Bar                  1
Mexican Restaurant        1
Used Bookstore            1
Gym                       1
Pub                       1
Lounge                    1
IT Services               1
Tea Room                  1
Big Box Store             1
Indian Restaurant         1
Wine Bar                  1
American Restaurant       1
Dim Sum Restaurant        1
Toy / Game Store          1
Cocktail Bar              1
Pizza Place               1
Moroccan Restaurant       1
Restaurant                1
Gym / Fitness Center      1
Performing Arts Venue     1
Food Court                1
Souvenir Shop             1
Italian Restaurant        1
Name: categories, dtype: int64

In [114]:
# View the Venues near San Pedro
nearby_venues_sp['categories'].value_counts()

Pizza Place             3
Coffee Shop             3
Italian Restaurant      2
Mexican Restaurant      2
Pharmacy                2
Fast Food Restaurant    2
Sandwich Place          2
Burger Joint            2
Breakfast Spot          1
Bakery                  1
Auto Garage             1
Bar                     1
Café                    1
Hardware Store          1
Deli / Bodega           1
Mobile Phone Shop       1
Sporting Goods Shop     1
Taco Place              1
Ice Cream Shop          1
Moroccan Restaurant     1
ATM                     1
Donut Shop              1
Video Store             1
Sports Bar              1
Bank                    1
Convenience Store       1
Fried Chicken Joint     1
Name: categories, dtype: int64

In [115]:
# View the Venues near Scarbourgh
nearby_venues_sb['categories'].value_counts()

Clothing Store         7
Coffee Shop            3
Sporting Goods Shop    3
Cosmetics Shop         3
Tea Room               2
Pharmacy               2
Sandwich Place         2
Department Store       1
Bakery                 1
Shopping Mall          1
Gym                    1
Electronics Store      1
Storage Facility       1
Food Court             1
Plaza                  1
Restaurant             1
Jewelry Store          1
Mexican Restaurant     1
Smoothie Shop          1
Pizza Place            1
Video Game Store       1
Movie Theater          1
Toy / Game Store       1
Big Box Store          1
Fish & Chips Shop      1
American Restaurant    1
Bank                   1
Discount Store         1
Greek Restaurant       1
Wings Joint            1
Name: categories, dtype: int64

In [124]:
# View the Venues near Avery Ranch
nearby_venues_av['categories'].value_counts()

Pool    1
Name: categories, dtype: int64

### Final Outcome : Generalizations and Clustering

Unfortunately, given data from foursqure was only focusing on Venues , while I am more interested in Parks & recreation areas in my neighbour so that I can play soccer a lot!!

Need to gather more data around the Neighbour/City from different sources. So that it can provide - Key factors like
Air quality,
Traffic,
Shoping ...

I will work on gettin more data from various sources contineously and try to gather input from different kind of people - Young,Senior..

Meantime, give me good points my friend !!

Thanks a lot !!